import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

const _unicodeVersion = '17.0.0';
const _sourceSha256 =
    'ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183';
const _defaultIgnorableSha256 =
    'fdfaaeddf73e63079c237c9e5f8c1a4be88391de0d8b3974093fad6f694c8a1f';
const _sourceUrl =
    'https://www.unicode.org/Public/$_unicodeVersion/ucd/CaseFolding.txt';
const _derivedPropertiesUrl =
    'https://www.unicode.org/Public/$_unicodeVersion/ucd/'
    'DerivedCoreProperties.txt';
const _commonFoldStatus = 'C';
const _fullFoldStatus = 'F';
const _simpleFoldStatus = 'S';
const _defaultIgnorableProperty = 'Default_Ignorable_Code_Point';

/// Regenerates the bundled table offline from the verified upstream fixture.
void main() {
  final source = File.fromUri(
    Platform.script.resolve('CaseFolding-$_unicodeVersion.txt'),
  );
  final bytes = source.readAsBytesSync();
  if (sha256.convert(bytes).toString() != _sourceSha256) {
    throw StateError('Unicode source hash differs from the pinned release.');
  }

  final mappings = <({int source, int target})>[];
  final fullExpansions = <({int source, List<int> targets})>[];
  for (final line in const LineSplitter().convert(utf8.decode(bytes))) {
    if (line.isEmpty || line.startsWith('#')) continue;

    final fields = line.split(';').map((field) => field.trim()).toList();
    if (fields[1] == _fullFoldStatus) {
      fullExpansions.add((
        source: int.parse(fields[0], radix: 16),
        targets: fields[2]
            .split(' ')
            .map((value) => int.parse(value, radix: 16))
            .toList(),
      ));
      continue;
    }
    if (fields[1] != _commonFoldStatus && fields[1] != _simpleFoldStatus) {
      continue;
    }

    mappings.add((
      source: int.parse(fields[0], radix: 16),
      target: int.parse(fields[2], radix: 16),
    ));
  }

  final ignorableSource = File.fromUri(
    Platform.script.resolve('DefaultIgnorable-$_unicodeVersion.txt'),
  );
  final ignorableBytes = ignorableSource.readAsBytesSync();
  if (sha256.convert(ignorableBytes).toString() != _defaultIgnorableSha256) {
    throw StateError(
      'Default-ignorable source hash differs from the pinned release.',
    );
  }

  final ignorableRanges = <({int start, int end})>[];
  for (final line in const LineSplitter().convert(
    utf8.decode(ignorableBytes),
  )) {
    if (line.isEmpty || line.startsWith('#')) continue;

    final fields = line.split(';');
    final property = fields[1].split('#').first.trim();
    if (property != _defaultIgnorableProperty) continue;

    final bounds = fields[0].trim().split('..');
    final start = int.parse(bounds.first, radix: 16);
    ignorableRanges.add((
      start: start,
      end: bounds.length == 1 ? start : int.parse(bounds.last, radix: 16),
    ));
  }

  // Collapse equal offsets at stride 1 or 2; ranges never overlap.
  final ranges = <({int start, int end, int stride, int delta})>[];
  for (var index = 0; index < mappings.length;) {
    final first = mappings[index];
    final delta = first.target - first.source;
    var end = index;
    var stride = 1;
    if (index + 1 < mappings.length) {
      final next = mappings[index + 1];
      final distance = next.source - first.source;
      if (distance <= 2 && next.target - next.source == delta) {
        stride = distance;
        end++;
      }
    }
    while (end + 1 < mappings.length &&
        mappings[end + 1].source - mappings[end].source == stride &&
        mappings[end + 1].target - mappings[end + 1].source == delta) {
      end++;
    }
    ranges.add((
      start: first.source,
      end: mappings[end].source,
      stride: stride,
      delta: delta,
    ));
    index = end + 1;
  }

  final output = StringBuffer()
    ..writeln('// Generated by tool/unicode/generate.dart. Do not edit.')
    ..writeln('// Source: $_sourceUrl')
    ..writeln('// SHA-256: $_sourceSha256')
    ..writeln('// Default-ignorable source: $_derivedPropertiesUrl')
    ..writeln('// Extract SHA-256: $_defaultIgnorableSha256')
    ..writeln(
      '// Copyright © 2025 Unicode, Inc. License: tool/unicode/LICENSE.txt',
    )
    ..writeln()
    ..writeln("part of 'unicode_simple_fold.dart';")
    ..writeln()
    ..writeln('// One range per constant offset; stride 2 skips uncased gaps.')
    ..writeln('// dart format off')
    ..writeln(
      'const _foldRanges = <({int start, int end, int stride, int delta})>[',
    );
  for (final range in ranges) {
    output.writeln(
      '  (start: ${_hex(range.start)}, end: ${_hex(range.end)}, '
      'stride: ${range.stride}, delta: ${range.delta}),',
    );
  }
  output.writeln('];');
  output
    ..writeln()
    ..writeln('// Full-fold mappings override their paired simple mapping.')
    ..writeln('const _fullFoldExpansions = <int, List<int>>{');
  for (final expansion in fullExpansions) {
    final targets = expansion.targets.map(_hex).join(', ');
    output.writeln('  ${_hex(expansion.source)}: [$targets],');
  }
  output.writeln('};');
  output
    ..writeln()
    ..writeln('// Unicode Default_Ignorable_Code_Point ranges.')
    ..writeln('const _defaultIgnorableRanges = <({int start, int end})>[');
  for (final range in ignorableRanges) {
    output.writeln('  (start: ${_hex(range.start)}, end: ${_hex(range.end)}),');
  }
  output.writeln('];');

  final destination = File.fromUri(
    Platform.script.resolve(
      '../../lib/src/browse/unicode_simple_fold_data.dart',
    ),
  );
  destination.writeAsStringSync(output.toString());
  stdout.writeln(
    '${mappings.length} simple mappings in ${ranges.length} ranges; '
    '${fullExpansions.length} full expansions; '
    '${ignorableRanges.length} default-ignorable ranges.',
  );
}

String _hex(int value) => '0x${value.toRadixString(16)}';
